; ---- Custom PHP configuration for Library app ----

display_errors = On
display_startup_errors = On
error_reporting = E_ALL
log_errors = On

date.timezone = Asia/Ho_Chi_Minh

upload_max_filesize = 10M
post_max_size = 12M
memory_limit = 256M
max_execution_time = 60

session.cookie_httponly = 1
session.use_strict_mode = 1
